### PR TITLE
Dinner Preparation Pull Request 

### PR DESCRIPTION
**Pull request by spg222**

### CODE REVIEW

**Comment by jklee-bear** [comment]
We don't a protein in our dinner ingredient! But we might need a cheese grinder for our Parmesan cheese?

**Review by jklee-bear — CHANGES_REQUESTED** [review]
We don't have any protein in dinner ingredient. Can we have a cheese grinder instead of grill for the protein?

**Comment by Tiffany-Shumate** [comment]
I like the idea of a cheese grinder, let's do it!

**Review by Tiffany-Shumate — COMMENTED** [review]
I added servings and time to prepare. Take a look!

**Comment by myronhc** [comment]
I love the idea of a cheese grinder too-- +1!

I think this recipe will slightly longer than we expect--   I'm going to change prep time to 40 minutes so that I have a commit on this recipe. Let me know what you all think!

**Comment by myronhc** [comment]
I just reread this discussion thread and modified the recipe to reflect what you tow discussed-- I removed the protein, and added the cheese grater.

**Pull request merged**
